from sqlalchemy import Column, Integer, VARCHAR, Float, Text
from sqlalchemy import MetaData
from sqlalchemy import Table


def varchar_column(name, chars=255):
    return Column(name, VARCHAR(chars), nullable=True)


def primary_varchar_column(name, chars=255):
    return Column(name, VARCHAR(chars), primary_key=True)


def float_column(name):
    return Column(name, Float, nullable=True)


def int_column(name):
    return Column(name, Integer, nullable=True)


def text_column(name):
    return Column(name, Text, nullable=True)


meta = MetaData()
game_log_table = Table(
    'game_log',
    meta,
    Column('SEASON_ID', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('TEAM_NAME', VARCHAR(255)),
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('GAME_DATE', VARCHAR(255)),
    Column('MATCHUP', VARCHAR(255)),
    Column('WL', VARCHAR(255)),
    Column('MIN', Float),
    Column('FGM', Float),
    Column('FGA', Float),
    Column('FG_PCT', Float),
    Column('FG3M', Float),
    Column('FG3A', Float),
    Column('FG3_PCT', Float),
    Column('FTM', Float),
    Column('FTA', Float),
    Column('FT_PCT', Float),
    Column('OREB', Float),
    Column('DREB', Float),
    Column('REB', Float),
    Column('AST', Float),
    Column('STL', Float),
    Column('BLK', Float),
    Column('TOV', Float),
    Column('PF', Float),
    Column('PTS', Float),
    Column('PLUS_MINUS', Float),
    Column('VIDEO_AVAILABLE', Integer),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255)))

team_box_score_traditional = Table(
    'team_box_score_traditional',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_NAME', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('TEAM_CITY', VARCHAR(255)),
    Column('MIN', Text),
    Column('FGM', Float),
    Column('FGA', Float),
    Column('FG_PCT', Float),
    Column('FG3M', Float),
    Column('FG3A', Float),
    Column('FG3_PCT', Float),
    Column('FTM', Float),
    Column('FTA', Float),
    Column('FT_PCT', Float),
    Column('OREB', Float),
    Column('DREB', Float),
    Column('REB', Float),
    Column('AST', Float),
    Column('STL', Float),
    Column('BLK', Float),
    Column('TOV', Float),
    Column('PF', Float),
    Column('PTS', Float),
    Column('PLUS_MINUS', Float),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255)))

team_box_score_advanced = Table(
    'team_box_score_advanced',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_NAME', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('TEAM_CITY', VARCHAR(255)),
    Column('MIN', Text),
    Column('E_OFF_RATING', Float),
    Column('OFF_RATING', Float),
    Column('E_DEF_RATING', Float),
    Column('DEF_RATING', Float),
    Column('E_NET_RATING', Float),
    Column('NET_RATING', Float),
    Column('AST_PCT', Float),
    Column('AST_TOV', Float),
    Column('AST_RATIO', Float),
    Column('OREB_PCT', Float),
    Column('DREB_PCT', Float),
    Column('REB_PCT', Float),
    Column('E_TM_TOV_PCT', Float),
    Column('TM_TOV_PCT', Float),
    Column('EFG_PCT', Float),
    Column('TS_PCT', Float),
    Column('USG_PCT', Float),
    Column('E_USG_PCT', Float),
    Column('E_PACE', Float),
    Column('PACE', Float),
    Column('PACE_PER40', Float),
    Column('POSS', Float),
    Column('PIE', Float),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

player_box_score_traditional = Table(
    'player_box_score_traditional',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('TEAM_CITY', VARCHAR(255)),
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('START_POSITION', VARCHAR(255)),
    Column('COMMENT', Text),
    Column('MIN', Text),
    Column('FGM', Float),
    Column('FGA', Float),
    Column('FG_PCT', Float),
    Column('FG3M', Float),
    Column('FG3A', Float),
    Column('FG3_PCT', Float),
    Column('FTM', Float),
    Column('FTA', Float),
    Column('FT_PCT', Float),
    Column('OREB', Float),
    Column('DREB', Float),
    Column('REB', Float),
    Column('AST', Float),
    Column('STL', Float),
    Column('BLK', Float),
    Column('TOV', Float),
    Column('PF', Float),
    Column('PTS', Float),
    Column('PLUS_MINUS', Float),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

player_box_score_advanced = Table(
    'player_box_score_advanced',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('TEAM_CITY', VARCHAR(255)),
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('START_POSITION', VARCHAR(255)),
    Column('COMMENT', Text),
    Column('MIN', Text),
    Column('E_OFF_RATING', Float),
    Column('OFF_RATING', Float),
    Column('E_DEF_RATING', Float),
    Column('DEF_RATING', Float),
    Column('E_NET_RATING', Float),
    Column('NET_RATING', Float),
    Column('AST_PCT', Float),
    Column('AST_TOV', Float),
    Column('AST_RATIO', Float),
    Column('OREB_PCT', Float),
    Column('DREB_PCT', Float),
    Column('REB_PCT', Float),
    Column('E_TM_TOV_PCT', Float),
    Column('TM_TOV_PCT', Float),
    Column('EFG_PCT', Float),
    Column('TS_PCT', Float),
    Column('USG_PCT', Float),
    Column('E_USG_PCT', Float),
    Column('E_PACE', Float),
    Column('PACE', Float),
    Column('PACE_PER40', Float),
    Column('POSS', Float),
    Column('PIE', Float),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

player_season_totals_traditional = Table(
    'player_season_totals_traditional',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('AGE', Float),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('W_PCT', Float),
    Column('MIN', Float),
    Column('FGM', Float),
    Column('FGA', Float),
    Column('FG_PCT', Float),
    Column('FG3M', Float),
    Column('FG3A', Float),
    Column('FG3_PCT', Float),
    Column('FTM', Float),
    Column('FTA', Float),
    Column('FT_PCT', Float),
    Column('OREB', Float),
    Column('DREB', Float),
    Column('REB', Float),
    Column('AST', Float),
    Column('TOV', Float),
    Column('STL', Float),
    Column('BLK', Float),
    Column('BLKA', Float),
    Column('PF', Float),
    Column('PFD', Float),
    Column('PTS', Float),
    Column('PLUS_MINUS', Float),
    Column('NBA_FANTASY_PTS', Float),
    Column('DD2', Float),
    Column('TD3', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_season_totals_advanced = Table(
    'player_season_totals_advanced',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('AGE', Float),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('W_PCT', Float),
    Column('MIN', Float),
    Column('OFF_RATING', Float),
    Column('DEF_RATING', Float),
    Column('NET_RATING', Float),
    Column('AST_PCT', Float),
    Column('AST_TO', Float),
    Column('AST_RATIO', Float),
    Column('OREB_PCT', Float),
    Column('DREB_PCT', Float),
    Column('REB_PCT', Float),
    Column('TM_TOV_PCT', Float),
    Column('EFG_PCT', Float),
    Column('TS_PCT', Float),
    Column('USG_PCT', Float),
    Column('PACE', Float),
    Column('PACE_PER40', Float),
    Column('PIE', Float),
    Column('POSS', Float),
    Column('FGM', Float),
    Column('FGA', Float),
    Column('FGM_PG', Float),
    Column('FGA_PG', Float),
    Column('FG_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_drives = Table(
    'player_tracking_drives',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('DRIVES', Float),
    Column('DRIVE_FGM', Float),
    Column('DRIVE_FGA', Float),
    Column('DRIVE_FG_PCT', Float),
    Column('DRIVE_FTM', Float),
    Column('DRIVE_FTA', Float),
    Column('DRIVE_FT_PCT', Float),
    Column('DRIVE_PTS', Float),
    Column('DRIVE_PTS_PCT', Float),
    Column('DRIVE_PASSES', Float),
    Column('DRIVE_PASSES_PCT', Float),
    Column('DRIVE_AST', Float),
    Column('DRIVE_AST_PCT', Float),
    Column('DRIVE_TOV', Float),
    Column('DRIVE_TOV_PCT', Float),
    Column('DRIVE_PF', Float),
    Column('DRIVE_PF_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_defense = Table(
    'player_tracking_defense',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('STL', Float),
    Column('BLK', Float),
    Column('DREB', Float),
    Column('DEF_RIM_FGM', Float),
    Column('DEF_RIM_FGA', Float),
    Column('DEF_RIM_FG_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_catch_and_shoot = Table(
    'player_tracking_catch_and_shoot',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('CATCH_SHOOT_FGM', Float),
    Column('CATCH_SHOOT_FGA', Float),
    Column('CATCH_SHOOT_FG_PCT', Float),
    Column('CATCH_SHOOT_PTS', Float),
    Column('CATCH_SHOOT_FG3M', Float),
    Column('CATCH_SHOOT_FG3A', Float),
    Column('CATCH_SHOOT_FG3_PCT', Float),
    Column('CATCH_SHOOT_EFG_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_passing = Table(
    'player_tracking_passing',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('PASSES_MADE', Float),
    Column('PASSES_RECEIVED', Float),
    Column('AST', Float),
    Column('FT_AST', Float),
    Column('SECONDARY_AST', Float),
    Column('POTENTIAL_AST', Float),
    Column('AST_PTS_CREATED', Float),
    Column('AST_ADJ', Float),
    Column('AST_TO_PASS_PCT', Float),
    Column('AST_TO_PASS_PCT_ADJ', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_touches = Table(
    'player_tracking_touches',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('POINTS', Float),
    Column('TOUCHES', Float),
    Column('FRONT_CT_TOUCHES', Float),
    Column('TIME_OF_POSS', Float),
    Column('AVG_SEC_PER_TOUCH', Float),
    Column('AVG_DRIB_PER_TOUCH', Float),
    Column('PTS_PER_TOUCH', Float),
    Column('ELBOW_TOUCHES', Float),
    Column('POST_TOUCHES', Float),
    Column('PAINT_TOUCHES', Float),
    Column('PTS_PER_ELBOW_TOUCH', Float),
    Column('PTS_PER_POST_TOUCH', Float),
    Column('PTS_PER_PAINT_TOUCH', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_pull_up_shots = Table(
    'player_tracking_pull_up_shots',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('PULL_UP_FGM', Float),
    Column('PULL_UP_FGA', Float),
    Column('PULL_UP_FG_PCT', Float),
    Column('PULL_UP_PTS', Float),
    Column('PULL_UP_FG3M', Float),
    Column('PULL_UP_FG3A', Float),
    Column('PULL_UP_FG3_PCT', Float),
    Column('PULL_UP_EFG_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_rebounds = Table(
    'player_tracking_rebounds',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('OREB', Float),
    Column('OREB_CONTEST', Float),
    Column('OREB_UNCONTEST', Float),
    Column('OREB_CONTEST_PCT', Float),
    Column('OREB_CHANCES', Float),
    Column('OREB_CHANCE_PCT', Float),
    Column('OREB_CHANCE_DEFER', Float),
    Column('OREB_CHANCE_PCT_ADJ', Float),
    Column('AVG_OREB_DIST', Float),
    Column('DREB', Float),
    Column('DREB_CONTEST', Float),
    Column('DREB_UNCONTEST', Float),
    Column('DREB_CONTEST_PCT', Float),
    Column('DREB_CHANCES', Float),
    Column('DREB_CHANCE_PCT', Float),
    Column('DREB_CHANCE_DEFER', Float),
    Column('DREB_CHANCE_PCT_ADJ', Float),
    Column('AVG_DREB_DIST', Float),
    Column('REB', Float),
    Column('REB_CONTEST', Float),
    Column('REB_UNCONTEST', Float),
    Column('REB_CONTEST_PCT', Float),
    Column('REB_CHANCES', Float),
    Column('REB_CHANCE_PCT', Float),
    Column('REB_CHANCE_DEFER', Float),
    Column('REB_CHANCE_PCT_ADJ', Float),
    Column('AVG_REB_DIST', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_efficiency = Table(
    'player_tracking_efficiency',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('POINTS', Float),
    Column('DRIVE_PTS', Float),
    Column('DRIVE_FG_PCT', Float),
    Column('CATCH_SHOOT_PTS', Float),
    Column('CATCH_SHOOT_FG_PCT', Float),
    Column('PULL_UP_PTS', Float),
    Column('PULL_UP_FG_PCT', Float),
    Column('PAINT_TOUCH_PTS', Float),
    Column('PAINT_TOUCH_FG_PCT', Float),
    Column('POST_TOUCH_PTS', Float),
    Column('POST_TOUCH_FG_PCT', Float),
    Column('ELBOW_TOUCH_PTS', Float),
    Column('ELBOW_TOUCH_FG_PCT', Float),
    Column('EFF_FG_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_speed_and_distance = Table(
    'player_tracking_speed_and_distance',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('DIST_FEET', Float),
    Column('DIST_MILES', Float),
    Column('DIST_MILES_OFF', Float),
    Column('DIST_MILES_DEF', Float),
    Column('AVG_SPEED', Float),
    Column('AVG_SPEED_OFF', Float),
    Column('AVG_SPEED_DEF', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_elbow_touches = Table(
    'player_tracking_elbow_touches',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('TOUCHES', Float),
    Column('ELBOW_TOUCHES', Float),
    Column('ELBOW_TOUCH_FGM', Float),
    Column('ELBOW_TOUCH_FGA', Float),
    Column('ELBOW_TOUCH_FG_PCT', Float),
    Column('ELBOW_TOUCH_FTM', Float),
    Column('ELBOW_TOUCH_FTA', Float),
    Column('ELBOW_TOUCH_FT_PCT', Float),
    Column('ELBOW_TOUCH_PTS', Float),
    Column('ELBOW_TOUCH_PTS_PCT', Float),
    Column('ELBOW_TOUCH_PASSES', Float),
    Column('ELBOW_TOUCH_PASSES_PCT', Float),
    Column('ELBOW_TOUCH_FG_PCT', Float),
    Column('ELBOW_TOUCH_AST', Float),
    Column('ELBOW_TOUCH_AST_PCT', Float),
    Column('ELBOW_TOUCH_TOV', Float),
    Column('ELBOW_TOUCH_TOV_PCT', Float),
    Column('ELBOW_TOUCH_FOULS', Float),
    Column('ELBOW_TOUCH_FOULS_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_post_touches = Table(
    'player_tracking_post_touches',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('TOUCHES', Float),
    Column('POST_TOUCHES', Float),
    Column('POST_TOUCH_FGM', Float),
    Column('POST_TOUCH_FGA', Float),
    Column('POST_TOUCH_FG_PCT', Float),
    Column('POST_TOUCH_FTM', Float),
    Column('POST_TOUCH_FTA', Float),
    Column('POST_TOUCH_FT_PCT', Float),
    Column('POST_TOUCH_PTS', Float),
    Column('POST_TOUCH_PTS_PCT', Float),
    Column('POST_TOUCH_PASSES', Float),
    Column('POST_TOUCH_PASSES_PCT', Float),
    Column('POST_TOUCH_AST', Float),
    Column('POST_TOUCH_AST_PCT', Float),
    Column('POST_TOUCH_TOV', Float),
    Column('POST_TOUCH_TOV_PCT', Float),
    Column('POST_TOUCH_FOULS', Float),
    Column('POST_TOUCH_FOULS_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

player_tracking_paint_touches = Table(
    'player_tracking_paint_touches',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('TEAM_ABBREVIATION', VARCHAR(255)),
    Column('GP', Float),
    Column('W', Float),
    Column('L', Float),
    Column('MIN', Float),
    Column('TOUCHES', Float),
    Column('PAINT_TOUCHES', Float),
    Column('PAINT_TOUCH_FGM', Float),
    Column('PAINT_TOUCH_FGA', Float),
    Column('PAINT_TOUCH_FG_PCT', Float),
    Column('PAINT_TOUCH_FTM', Float),
    Column('PAINT_TOUCH_FTA', Float),
    Column('PAINT_TOUCH_FT_PCT', Float),
    Column('PAINT_TOUCH_PTS', Float),
    Column('PAINT_TOUCH_PTS_PCT', Float),
    Column('PAINT_TOUCH_PASSES', Float),
    Column('PAINT_TOUCH_PASSES_PCT', Float),
    Column('PAINT_TOUCH_AST', Float),
    Column('PAINT_TOUCH_AST_PCT', Float),
    Column('PAINT_TOUCH_TOV', Float),
    Column('PAINT_TOUCH_TOV_PCT', Float),
    Column('PAINT_TOUCH_FOULS', Float),
    Column('PAINT_TOUCH_FOULS_PCT', Float),
    Column('SEASON', VARCHAR(255), primary_key=True),
    Column('SEASON_TYPE', VARCHAR(255), primary_key=True)
)

play_by_play = Table(
    'play_by_play',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('EVENTNUM', Integer, primary_key=True),
    Column('EVENTMSGTYPE', Integer),
    Column('EVENTMSGACTIONTYPE', Integer),
    Column('PERIOD', Integer),
    Column('WCTIMESTRING', VARCHAR(255)),
    Column('PCTIMESTRING', VARCHAR(255)),
    Column('HOMEDESCRIPTION', Text),
    Column('NEUTRALDESCRIPTION', Text),
    Column('VISITORDESCRIPTION', Text),
    Column('SCORE', VARCHAR(255)),
    Column('SCOREMARGIN', VARCHAR(255)),
    Column('PERSON1TYPE', VARCHAR(255)),
    Column('PLAYER1_ID', VARCHAR(255)),
    Column('PLAYER1_NAME', VARCHAR(255)),
    Column('PLAYER1_TEAM_ID', VARCHAR(255)),
    Column('PLAYER1_TEAM_CITY', VARCHAR(255)),
    Column('PLAYER1_TEAM_NICKNAME', VARCHAR(255)),
    Column('PLAYER1_TEAM_ABBREVIATION', VARCHAR(255)),
    Column('PERSON2TYPE', VARCHAR(255)),
    Column('PLAYER2_ID', VARCHAR(255)),
    Column('PLAYER2_NAME', VARCHAR(255)),
    Column('PLAYER2_TEAM_ID', VARCHAR(255)),
    Column('PLAYER2_TEAM_CITY', VARCHAR(255)),
    Column('PLAYER2_TEAM_NICKNAME', VARCHAR(255)),
    Column('PLAYER2_TEAM_ABBREVIATION', VARCHAR(255)),
    Column('PERSON3TYPE', VARCHAR(255)),
    Column('PLAYER3_ID', VARCHAR(255)),
    Column('PLAYER3_NAME', VARCHAR(255)),
    Column('PLAYER3_TEAM_ID', VARCHAR(255)),
    Column('PLAYER3_TEAM_CITY', VARCHAR(255)),
    Column('PLAYER3_TEAM_NICKNAME', VARCHAR(255)),
    Column('PLAYER3_TEAM_ABBREVIATION', VARCHAR(255)),
    Column('VIDEO_AVAILABLE_FLAG', VARCHAR(255)),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

players_on_court_per_period = Table(
    'players_on_court_per_period',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('PERIOD', Integer, primary_key=True),
    Column('PLAYER_ID', VARCHAR(255), primary_key=True),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_ID', VARCHAR(255)),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

shot_chart_detail = Table(
    'shot_chart_detail',
    meta,
    Column('PLAYER_ID', VARCHAR(255), primary_key=True, index=True),
    Column('GAME_ID', VARCHAR(255), primary_key=True, index=True),
    Column('TEAM_ID', VARCHAR(255), index=True),
    Column('GAME_EVENT_ID', Integer, primary_key=True),

    Column('GRID_TYPE', VARCHAR(255)),
    Column('PLAYER_NAME', VARCHAR(255)),
    Column('TEAM_NAME', VARCHAR(255)),
    Column('PERIOD', Integer),
    Column('MINUTES_REMAINING', Integer),
    Column('SECONDS_REMAINING', Integer),
    Column('EVENT_TYPE', VARCHAR(255)),
    Column('ACTION_TYPE', VARCHAR(255)),
    Column('SHOT_TYPE', VARCHAR(255)),
    Column('SHOT_ZONE_BASIC', VARCHAR(255)),
    Column('SHOT_ZONE_AREA', VARCHAR(255)),
    Column('SHOT_ZONE_RANGE', VARCHAR(255)),

    Column('SHOT_DISTANCE', Integer),
    Column('LOC_X', Integer),
    Column('LOC_Y', Integer),
    Column('SHOT_ATTEMPTED_FLAG', Integer),
    Column('SHOT_MADE_FLAG', Integer),

    Column('GAME_DATE', VARCHAR(255)),
    Column('HTM', VARCHAR(255)),
    Column('VTM', VARCHAR(255)),

    Column('SEASON', VARCHAR(255), index=True),
    Column('SEASON_TYPE', VARCHAR(255), index=True)
)

win_probability = Table(
    'win_probability',
    meta,
    Column('GAME_ID', VARCHAR(255), primary_key=True),
    Column('PERIOD', Integer, primary_key=True),
    Column('EVENT_NUM', VARCHAR(255), primary_key=True),
    Column('HOME_PCT', Float, nullable=True),
    Column('VISITOR_PCT', Float, nullable=True),
    Column('HOME_PTS', Integer, nullable=True),
    Column('VISITOR_PTS', Integer, nullable=True),
    Column('HOME_SCORE_MARGIN', Integer, nullable=True),
    Column('SECONDS_REMAINING', Integer, primary_key=True),
    Column('HOME_POSS_IND', Integer, nullable=True),
    Column('HOME_G', Integer, nullable=True),
    Column('DESCRIPTION', Text, nullable=True),
    Column('LOCATION', VARCHAR(255), nullable=True),
    Column('PCTIMESTRING', VARCHAR(255), nullable=True),
    Column('ISVISIBLE', Integer, nullable=True),
    Column('SEASON', VARCHAR(255)),
    Column('SEASON_TYPE', VARCHAR(255))
)

closet_defender_shooting = Table(
    'shot_dashboard_closet_defender_shooting',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("CLOSE_DEF_DIST_RANGE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)

closet_defender_shooting_10_plus = Table(
    'shot_dashboard_closet_defender_shooting_10_plust',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("CLOSE_DEF_DIST_RANGE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)

touch_time_shooting = Table(
    'shot_dashboard_touch_time_shooting',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("TOUCH_TIME_RANGE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)

dribble_shooting = Table(
    'shot_dashboard_dribble_shooting',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("DRIBBLE_RANGE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)

shot_clock_shooting = Table(
    'shot_dashboard_shot_clock_shooting',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("SHOT_CLOCK_RANGE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)

general_shooting = Table(
    'shot_dashboard_general_shooting',
    meta,
    primary_varchar_column("PLAYER_ID", chars=20),
    text_column("PLAYER_NAME_LAST_FIRST"),
    text_column("SORT_ORDER"),
    int_column("GP"),
    int_column("G"),
    primary_varchar_column("SHOT_TYPE"),
    float_column("FGA_FREQUENCY"),
    int_column("FGM"),
    int_column("FGA"),
    float_column("FG_PCT"),
    float_column("EFG_PCT"),
    float_column("FG2A_FREQUENCY"),
    int_column("FG2M"),
    int_column("FG2A"),
    float_column("FG2_PCT"),
    float_column("FG3A_FREQUENCY"),
    int_column("FG3M"),
    int_column("FG3A"),
    float_column("FG3_PCT"),
    primary_varchar_column("SEASON", chars=20),
    primary_varchar_column("SEASON_TYPE"),
)